strictness: veryhigh
test-warnings: true
doc-warnings: false

pylint:
    disable:
        # Disabled in the interest of supporting python2
        - consider-using-f-string
        # Disabled because pre-commit does not pick up dependencies
        - import-error
        # Python2 lacks dataclasses
        - too-few-public-methods
        # Disabled for inheriting from `object` in python2
        - useless-object-inheritance
        # Necessary to suport python 2
        - super-with-arguments
    options:
        # Allows variables like the following:
        # i, to, abc_def, abc_DEF, to_M_series
        # Denies variables like the following:
        # I, M_series, camelCase,
        variable-rgx: ^([_a-z][a-z0-9]*)((_([a-z0-9]+|[A-Z0-9]+))*)?$
        argument-rgx: ^([_a-z][a-z0-9]*)((_([a-z0-9]+|[A-Z0-9]+))*)?$
        # Let black.exe to handle the line length
        # Could not be disabled, so 100 is used to bypass it
        max-line-length: 100
pep8:
    options:
        # Let black.exe to handle the line length
        # Could not be disabled, so 100 is used to bypass it
        max-line-length: 100
    disable:
        - N802
